[CmdletBinding()]
param(
    [string]$SourceRepo = "https://github.com/eljaunis/awesome-cursorrules.git",
    [string]$SourceRef = "main",
    [string]$CodexHome = $(if ($env:CODEX_HOME) { $env:CODEX_HOME } else { Join-Path $HOME ".codex" }),
    [switch]$NoGlobalAgents,
    [switch]$Force
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Get-Sha8([string]$Value) {
    $sha = [System.Security.Cryptography.SHA256]::Create()
    try {
        $bytes = [System.Text.Encoding]::UTF8.GetBytes($Value)
        $hash = $sha.ComputeHash($bytes)
        return ([System.BitConverter]::ToString($hash).Replace("-", "").ToLowerInvariant()).Substring(0, 8)
    }
    finally { $sha.Dispose() }
}

function Convert-ToSkillName([string]$Stem) {
    $slug = $Stem.ToLowerInvariant() -replace '[^a-z0-9]+', '-'
    $slug = $slug.Trim('-')
    if (-not $slug) { $slug = "rule" }
    $prefix = "cursorrule-"
    $maxLen = 63
    $candidate = $prefix + $slug
    if ($candidate.Length -le $maxLen) { return $candidate }
    $suffix = "-" + (Get-Sha8 $Stem)
    $take = $maxLen - $prefix.Length - $suffix.Length
    return $prefix + $slug.Substring(0, [Math]::Max(1, $take)).Trim('-') + $suffix
}

function Escape-YamlDoubleQuoted([string]$Value) {
    return $Value.Replace('\', '\\').Replace('"', '\"').Replace("`r", " ").Replace("`n", " ")
}

function Parse-Mdc([string]$Text, [string]$FallbackDescription) {
    $description = $FallbackDescription
    $globs = ""
    $alwaysApply = "false"
    $body = $Text

    if ($Text -match '(?s)^---\s*\r?\n(.*?)\r?\n---\s*\r?\n?(.*)$') {
        $front = $Matches[1]
        $body = $Matches[2]
        if ($front -match '(?m)^description:\s*["'']?(.*?)["'']?\s*$') { $description = $Matches[1].Trim() }
        if ($front -match '(?m)^globs:\s*(.*?)\s*$') { $globs = $Matches[1].Trim() }
        if ($front -match '(?m)^alwaysApply:\s*(.*?)\s*$') { $alwaysApply = $Matches[1].Trim().ToLowerInvariant() }
    }

    [pscustomobject]@{
        Description = $description
        Globs = $globs
        AlwaysApply = $alwaysApply
        Body = $body.Trim()
    }
}

$skillsRoot = Join-Path $CodexHome "skills"
New-Item -ItemType Directory -Force -Path $skillsRoot | Out-Null

$temp = $null
$sourceRoot = $null
$scriptRepoRoot = Split-Path -Parent $PSScriptRoot
if ($PSScriptRoot -and (Test-Path (Join-Path $scriptRepoRoot "rules"))) {
    $sourceRoot = $scriptRepoRoot
}
else {
    if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
        throw "Git is required when the installer is not run from a clone of awesome-cursorrules."
    }
    $temp = Join-Path ([System.IO.Path]::GetTempPath()) ("awesome-cursorrules-" + [guid]::NewGuid().ToString("N"))
    git clone --depth 1 --branch $SourceRef $SourceRepo $temp | Out-Host
    $sourceRoot = $temp
}

try {
    $ruleFiles = Get-ChildItem -Path (Join-Path $sourceRoot "rules") -Filter "*.mdc" -File -Recurse
    if (-not $ruleFiles) { throw "No .mdc rule files found under $sourceRoot\rules" }

    $installed = 0
    foreach ($file in $ruleFiles) {
        $stem = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
        $skillName = Convert-ToSkillName $stem
        $raw = Get-Content -LiteralPath $file.FullName -Raw -Encoding UTF8
        $parsed = Parse-Mdc $raw "Guidance for $stem."

        $desc = $parsed.Description
        $desc = $desc -replace '(?i)^cursor rules? for\s*', ''
        $desc = $desc -replace '(?i)^cursorrules? for\s*', ''
        $desc = $desc.Trim().TrimEnd('.')
        if (-not $desc) { $desc = "Guidance for $stem" }

        $activation = "Use when the current software task or repository matches: $desc."
        if ($parsed.Globs) { $activation += " Original Cursor file scope: $($parsed.Globs)." }
        $activation += " Do not use for unrelated stacks; prefer a narrower matching skill when several rules overlap."
        $yamlDescription = Escape-YamlDoubleQuoted $activation

        $skillDir = Join-Path $skillsRoot $skillName
        $skillFile = Join-Path $skillDir "SKILL.md"
        if ((Test-Path $skillFile) -and -not $Force) {
            # Files generated by this installer are safe to refresh. Preserve hand-edited foreign skills.
            $existing = Get-Content -LiteralPath $skillFile -Raw -Encoding UTF8
            if ($existing -notmatch 'Source: awesome-cursorrules/') {
                Write-Warning "Skipping existing non-generated skill: $skillName (use -Force to replace)"
                continue
            }
        }
        New-Item -ItemType Directory -Force -Path $skillDir | Out-Null

        $relative = $file.FullName.Substring($sourceRoot.Length).TrimStart('\','/').Replace('\','/')
        $scopeText = if ($parsed.Globs) { $parsed.Globs } else { "not specified" }
        $content = @"
---
name: $skillName
description: "$yamlDescription"
---

# $stem

Source: awesome-cursorrules/$relative
Original `alwaysApply`: $($parsed.AlwaysApply)
Original Cursor globs: $scopeText

## Activation discipline

Apply this skill only when the repository, files, framework, language, or task clearly match the rule. Inspect the repository before assuming a stack. If another installed skill is more specific, prefer the more specific skill. If two skills conflict, follow the repository's actual versions and conventions, current authoritative documentation, and the narrower applicable skill rather than combining contradictory guidance.

## Rule

$($parsed.Body)
"@
        Set-Content -LiteralPath $skillFile -Value $content -Encoding UTF8
        $installed++
    }

    # Copy any existing Agent Skills packages in the source repository, if present.
    $existingSkillFiles = Get-ChildItem -Path $sourceRoot -Filter "SKILL.md" -File -Recurse | Where-Object {
        $_.FullName -notmatch '[\\/]\.git[\\/]' -and $_.FullName -notmatch '[\\/]node_modules[\\/]'
    }
    foreach ($skill in $existingSkillFiles) {
        $raw = Get-Content -LiteralPath $skill.FullName -Raw -Encoding UTF8
        if ($raw -notmatch '(?m)^name:\s*["'']?([^"''\r\n]+)') { continue }
        $skillName = ($Matches[1].Trim() -replace '[^a-zA-Z0-9._-]', '-')
        $targetDir = Join-Path $skillsRoot $skillName
        if (Test-Path $targetDir) {
            Write-Warning "Existing skill '$skillName' already present; leaving it unchanged."
            continue
        }
        Copy-Item -LiteralPath $skill.Directory.FullName -Destination $targetDir -Recurse
        $installed++
    }

    # Install a lightweight router. Its description makes Codex consider it automatically for coding work.
    $routerDir = Join-Path $skillsRoot "awesome-cursorrules-router"
    New-Item -ItemType Directory -Force -Path $routerDir | Out-Null
    $router = @'
---
name: awesome-cursorrules-router
description: "Use at the start of software implementation, debugging, refactoring, code review, architecture, testing, deployment, database, security, frontend, backend, mobile, or framework-specific tasks to select the narrowest relevant installed cursorrule-* skills based on the repository's actual stack. Do not use unrelated framework rules."
---

# Awesome Cursor Rules router

Before changing code:

1. Inspect the repository's manifests, lockfiles, config files, extensions, imports, and existing conventions to identify the actual language, framework, versions, runtime, database, test framework, deployment platform, and UI stack.
2. Review the installed `cursorrule-*` skill names/descriptions exposed by Codex and load only those clearly relevant to this task.
3. Prefer narrow, version-specific skills over broad or older skills.
4. Do not combine mutually exclusive framework or version rules merely because they are installed.
5. Repository-local `AGENTS.md`, explicit user instructions, existing code conventions, tests, and current authoritative documentation outrank generic migrated rules.
6. If a migrated rule appears stale or conflicts with the installed dependency version, verify current documentation and follow the current API.
7. Use general quality/security/testing skills only when they add task-relevant constraints; avoid loading a large bundle by default.

The purpose of this router is selection, not to make every installed rule active simultaneously.
'@
    Set-Content -LiteralPath (Join-Path $routerDir "SKILL.md") -Value $router -Encoding UTF8

    if (-not $NoGlobalAgents) {
        $globalAgents = Join-Path $HOME "AGENTS.md"
        $begin = "<!-- BEGIN awesome-cursorrules Codex routing -->"
        $end = "<!-- END awesome-cursorrules Codex routing -->"
        $block = @"
$begin
## Awesome Cursor Rules / Codex skills

For software engineering tasks, use the `awesome-cursorrules-router` skill to identify the repository's actual stack and then load only the narrowest relevant installed `cursorrule-*` skills. Never activate all migrated rules at once. Do not apply rules for frameworks, languages, versions, databases, test tools, or deployment platforms that are not present in the current task/repository. Repository-local `AGENTS.md`, explicit instructions, actual dependency versions, tests, and current authoritative documentation take precedence over generic migrated rules.
$end
"@
        $existing = if (Test-Path $globalAgents) { Get-Content -LiteralPath $globalAgents -Raw -Encoding UTF8 } else { "" }
        $pattern = '(?s)' + [regex]::Escape($begin) + '.*?' + [regex]::Escape($end)
        if ($existing -match $pattern) {
            $updated = [regex]::Replace($existing, $pattern, [System.Text.RegularExpressions.MatchEvaluator]{ param($m) $block.Trim() })
        }
        else {
            $separator = if ($existing.Trim()) { "`r`n`r`n" } else { "" }
            $updated = $existing.TrimEnd() + $separator + $block.Trim() + "`r`n"
        }
        Set-Content -LiteralPath $globalAgents -Value $updated -Encoding UTF8
        Write-Host "Updated global Codex instructions: $globalAgents"
    }

    Write-Host "Installed/refreshed $installed migrated skills plus awesome-cursorrules-router in: $skillsRoot"
    Write-Host "Restart Codex completely, then start a new thread so skill discovery is refreshed."
}
finally {
    if ($temp -and (Test-Path $temp)) { Remove-Item -LiteralPath $temp -Recurse -Force -ErrorAction SilentlyContinue }
}
